### ISSUE TITLE
switch to !!sym() syntax instead?

### ISSUE THREAD

**Issue by firasm** [matthewconnell/dashr_sample_layouts#4]
hey @matthewconnell 

I noticed that your sample layouts have ggplots in this syntax with xaxis coming as an argument for a function.

```
ggplot(data = df, aes(x=df[[xaxis]]))
```

From the [tabs layout](https://github.com/matthewconnell/dashr_sample_layouts/blob/master/basic-tabs/app.R)

I think we better change this to `!!sym(xaxis)` instead. I think both are right, but this way is more preferred in functional programming (I think anyway).

Let me know what you think

**Comment by matthewconnell** [comment]
Oh, nice catch. I was trying to remember what the syntax was for that when I was making it.

Changed on all three layouts.

(Commit: 471106bb9a8ac0280dee15485c5fcbb96a5ce1b2)
